# name of the action
name: reviewdog

# trigger on pull_request events
on:
  pull_request:

permissions:
  contents: read

# pipeline to execute
jobs:
  diff-review:
    runs-on: ubuntu-latest

    permissions:
      contents: read # for actions/checkout to fetch code
      pull-requests: write # for reviewdog/action-golangci-lint to report issues using PR comments

    steps:
      - name: clone
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: install go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          # use version from go.mod file
          go-version-file: "go.mod"
          cache: true
          check-latest: true

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@c76cceaaab89abe74e649d2e34c6c9adc26662d2 # v2.10.0
        with:
          github_token: ${{ secrets.github_token }}
          golangci_lint_flags: "--config=.golangci.yml --timeout=5m"
          fail_level: error
          filter_mode: diff_context
          reporter: github-pr-review

  full-review:
    runs-on: ubuntu-latest

    permissions:
      checks: write # for reviewdog/action-golangci-lint to report issues using checks
      contents: read # for actions/checkout to fetch code

    steps:
      - name: clone
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: install go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          # use version from go.mod file
          go-version-file: "go.mod"
          cache: true
          check-latest: true

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@c76cceaaab89abe74e649d2e34c6c9adc26662d2 # v2.10.0
        with:
          github_token: ${{ secrets.github_token }}
          golangci_lint_flags: "--config=.golangci.yml --timeout=5m"
          fail_level: error
          filter_mode: nofilter
