# name of the action
name: test

# trigger on pull_request or push events
on:
  pull_request:
  push:

permissions:
  contents: read

# pipeline to execute
jobs:
  test:
    runs-on: ubuntu-latest

    # for codecov report upload
    permissions:
      id-token: write

    steps:
      - name: clone
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: install go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          # use version from go.mod file
          go-version-file: "go.mod"
          cache: true
          check-latest: true

      - name: test
        run: |
          make test

      - name: test jsonschema
        run: |
          go install github.com/santhosh-tekuri/jsonschema/cmd/jv@v0.7.0
          make test-jsonschema

      - name: coverage
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v6.0.2
        with:
          use_oidc: true
          files: coverage.out
