# name of the action
name: test

# trigger on pull_request or push events
on:
  pull_request:
  push:

permissions:
  contents: read

# pipeline to execute
jobs:
  test:
    runs-on: ubuntu-latest

    # for codecov report upload
    permissions:
      id-token: write

    steps:
      - name: clone
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: install go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          # use version from go.mod file
          go-version-file: "go.mod"
          cache: true
          check-latest: true

      - name: test
        run: |
          make test

      - name: test jsonschema
        run: |
          go install github.com/santhosh-tekuri/jsonschema/cmd/jv@v0.7.0
          make test-jsonschema

      - name: coverage
        uses: codecov/codecov-action@fdcc8476540edceab3de004e990f80d881c6cc00 # v5.5.0
        with:
          use_oidc: true
          files: coverage.out
